export const conteudos = [
  { arquivo: "fundamentos.html", titulo: "Gênero dos substantivos", descricao: "der, die, das; aprender substantivos com o artigo", categoria: "Fundamentos", tag: "Fundamentos" },
  { arquivo: "artigos-definidos.html", titulo: "Artigos definidos", descricao: "der/die/das/die e suas formas nos quatro casos", categoria: "Artigos e casos", tag: "Gramática" },
  { arquivo: "artigos-indefinidos.html", titulo: "Artigos indefinidos", descricao: "ein/eine/ein e suas formas nos casos", categoria: "Artigos e casos", tag: "Gramática" },
  { arquivo: "casos.html", titulo: "Os quatro casos", descricao: "Nominativ, Akkusativ, Dativ e Genitiv", categoria: "Artigos e casos", tag: "Gramática" },
  { arquivo: "negacao.html", titulo: "Negação: nicht e kein", descricao: "quando usar nicht e quando usar kein", categoria: "Artigos e casos", tag: "Gramática" },
  { arquivo: "pronomes.html", titulo: "Pronomes pessoais", descricao: "pronomes pessoais nos casos, posição na frase, es impessoal e Sie/sie", categoria: "Artigos e casos", tag: "Gramática" },
  { arquivo: "dativ.html", titulo: "Dativ", descricao: "artigos, preposições e verbos relacionados ao Dativ", categoria: "Artigos e casos", tag: "Gramática" },
  { arquivo: "ndeklination.html", titulo: "n-Deklination", descricao: "substantivos masculinos com formas especiais", categoria: "Artigos e casos", tag: "Gramática" },
  { arquivo: "presente-regulares.html", titulo: "Presente: verbos regulares", descricao: "conjugação e terminações no presente", categoria: "Verbos", tag: "Verbos" },
  { arquivo: "presente-irregulares.html", titulo: "Presente: verbos irregulares", descricao: "mudanças no radical em verbos frequentes", categoria: "Verbos", tag: "Verbos" },
  { arquivo: "modais.html", titulo: "Verbos modais", descricao: "können e outros modais estudados", categoria: "Verbos", tag: "Verbos" },
  { arquivo: "separaveis.html", titulo: "Verbos separáveis", descricao: "prefixos separáveis, posição na frase, modais, subordinadas e Partizip II", categoria: "Verbos", tag: "Verbos" },
  { arquivo: "reflexivos.html", titulo: "Verbos reflexivos", descricao: "pronomes reflexivos, Akkusativ/Dativ, posição na frase, Perfekt e preposições fixas", categoria: "Verbos", tag: "Verbos" },
  { arquivo: "perfekt.html", titulo: "Perfekt", descricao: "haben/sein + Partizip II", categoria: "Verbos", tag: "Verbos" },
  { arquivo: "futur-1.html", titulo: "Futur I", descricao: "werden + infinitivo para previsões, suposições e ênfase no futuro", categoria: "Verbos", tag: "Verbos" },
  { arquivo: "prateritum.html", titulo: "Präteritum", descricao: "passado usado sobretudo na escrita e com sein, haben e verbos modais", categoria: "Verbos", tag: "Verbos" },
  { arquivo: "ordem-frase.html", titulo: "Ordem das palavras", descricao: "posição do verbo e inversão", categoria: "Estrutura das frases", tag: "Estrutura" },
  { arquivo: "subordinadas.html", titulo: "Orações subordinadas", descricao: "weil, dass, wenn, als, ob e outras conjunções subordinativas", categoria: "Estrutura das frases", tag: "Estrutura" },
  { arquivo: "preposicoes.html", titulo: "Preposições", descricao: "mit, bei, von, zu, aus, nach e outras", categoria: "Preposições", tag: "Preposições" },
  { arquivo: "wechsel.html", titulo: "Wechselpräpositionen", descricao: "movimento/direção x localização", categoria: "Preposições", tag: "Preposições" },
  { arquivo: "adjetivos.html", titulo: "Adjetivos", descricao: "declinação com artigos definidos, indefinidos e sem artigo", categoria: "Adjetivos e vocabulário", tag: "Gramática" },
  { arquivo: "vocabulario_substantivos.html", titulo: "Vocabulário de substantivos acumulado", descricao: "palavras e expressões trabalhadas durante o percurso", categoria: "Adjetivos e vocabulário", tag: "Vocabulário" },
  { arquivo: "indefinidos-plural.html", titulo: "Indefinidos no plural", descricao: "einige, manche e ausência de artigo", categoria: "Adjetivos e vocabulário", tag: "Gramática" }
];
