export const conteudos = [
  { arquivo: "generos.html", titulo: "Gênero dos substantivos", descricao: "der, die, das; aprender substantivos com o artigo", categoria: "Substantivos", tag: "Gramática" },
  { arquivo: "artigos-definidos.html", titulo: "Artigos definidos", descricao: "der/die/das/die e suas formas nos quatro casos", categoria: "Artigos e casos", tag: "Gramática" },
  { arquivo: "artigos-indefinidos.html", titulo: "Artigos indefinidos", descricao: "ein/eine/ein e suas formas nos casos", categoria: "Artigos e casos", tag: "Gramática" },
  { arquivo: "casos.html", titulo: "Os quatro casos", descricao: "Nominativ, Akkusativ, Dativ e Genitiv", categoria: "Artigos e casos", tag: "Gramática" },
  { arquivo: "negacao.html", titulo: "Negação: nicht e kein", descricao: "quando usar nicht e quando usar kein", categoria: "Artigos e casos", tag: "Gramática" },
  { arquivo: "pronomes-pessoais.html", titulo: "Pronomes pessoais", descricao: "pronomes pessoais nos casos, posição na frase, es impessoal e Sie/sie", categoria: "Pronomes", tag: "Gramática" },
  { arquivo: "pronomes-possessivos.html", titulo: "Pronomes possessivos", descricao: "formas possessivas e declinação conforme gênero, número e caso", categoria: "Pronomes", tag: "Gramática" },
  { arquivo: "pronomes-demonstrativos.html", titulo: "Pronomes demonstrativos", descricao: "dieser, jener, derselbe, solcher e formas demonstrativas com der/die/das", categoria: "Pronomes", tag: "Gramática" },
  { arquivo: "dativ.html", titulo: "Dativ", descricao: "artigos, preposições e verbos relacionados ao Dativ", categoria: "Artigos e casos", tag: "Gramática" },
  { arquivo: "ndeklination.html", titulo: "n-Deklination", descricao: "substantivos masculinos com formas especiais", categoria: "Artigos e casos", tag: "Gramática" },
  { arquivo: "presente-regulares.html", titulo: "Presente: verbos regulares", descricao: "conjugação e terminações no presente", categoria: "Verbos", tag: "Verbos" },
  { arquivo: "presente-irregulares.html", titulo: "Presente: verbos irregulares", descricao: "mudanças no radical em verbos frequentes", categoria: "Verbos", tag: "Verbos" },
  { arquivo: "modais.html", titulo: "Verbos modais", descricao: "können e outros modais estudados", categoria: "Verbos", tag: "Verbos" },
  { arquivo: "separaveis.html", titulo: "Verbos separáveis", descricao: "prefixos separáveis, posição na frase, modais, subordinadas e Partizip II", categoria: "Verbos", tag: "Verbos" },
  { arquivo: "reflexivos.html", titulo: "Verbos reflexivos", descricao: "pronomes reflexivos, Akkusativ/Dativ, posição na frase, Perfekt e preposições fixas", categoria: "Verbos", tag: "Verbos" },
  { arquivo: "perfekt.html", titulo: "Perfekt", descricao: "haben/sein + Partizip II", categoria: "Verbos", tag: "Verbos" },
  { arquivo: "futur-1.html", titulo: "Futur I", descricao: "werden + infinitivo para previsões, suposições e ênfase no futuro", categoria: "Verbos", tag: "Verbos" },
  { arquivo: "prateritum.html", titulo: "Präteritum", descricao: "passado usado sobretudo na escrita e com sein, haben e verbos modais", categoria: "Verbos", tag: "Verbos" },
  { arquivo: "verbos/vocabulario_verbos.html", titulo: "Vocabulário Verbos", descricao: "lista de verbos com significados e conjugações", categoria: "Verbos", tag: "Verbos" },
  { arquivo: "stehen-stellen-liegen-legen.html", titulo: "Stehen, Stellen, Liegen, Legen", descricao: "Quando usar Stehen, Stellen, Liegen, Legen", categoria: "Verbos", tag: "Verbos" },
  { arquivo: "ordem-frase.html", titulo: "Ordem das palavras", descricao: "posição do verbo e inversão", categoria: "Estrutura das frases", tag: "Estrutura" },
  { arquivo: "subordinadas.html", titulo: "Orações subordinadas", descricao: "weil, dass, wenn, als, ob e outras conjunções subordinativas", categoria: "Estrutura das frases", tag: "Estrutura" },
  { arquivo: "preposicoes.html", titulo: "Preposições", descricao: "mit, bei, von, zu, aus, nach e outras", categoria: "Preposições", tag: "Preposições" },
  { arquivo: "wechsel.html", titulo: "Wechselpräpositionen", descricao: "movimento/direção x localização", categoria: "Preposições", tag: "Preposições" },
  { arquivo: "verbos-preposicionais.html", titulo: "Verbos preposicionais", descricao: "verbos com preposição fixa, casos, wo(r)-/da(r)-, tempos verbais e subordinadas", categoria: "Verbos", tag: "Gramática" },
  { arquivo: "adjetivos.html", titulo: "Adjetivos", descricao: "declinação com artigos definidos, indefinidos e sem artigo", categoria: "Adjetivos", tag: "Gramática" },
  { arquivo: "vocabulario_substantivos.html", titulo: "Vocabulário de substantivos acumulado", descricao: "palavras e expressões trabalhadas durante o percurso", categoria: "Substantivos", tag: "Vocabulário" },
  { arquivo: "indefinidos-plural.html", titulo: "Indefinidos no plural", descricao: "einige, manche e ausência de artigo", categoria: "Adjetivos", tag: "Gramática" },
  { arquivo: "pronomes-relativos.html", titulo: "Pronomes Relativos", descricao: "Pronomes Relativos", categoria: "Pronomes", tag: "Gramática" },
  { arquivo: "comparativo-superlativo.html", titulo: "Comparativo e Superlativo", descricao: "Formação e uso do comparativo e superlativo", categoria: "Adjetivos", tag: "Gramática" },
  { arquivo: "vocabulario-adjetivos.html", titulo: "Vocabulário de Adjetivos", descricao: "lista de adjetivos com significados e declinações", categoria: "Adjetivos", tag: "Gramática" },
  { arquivo: "vocabulario-adverbios.html", titulo: "Vocabulário de Advérbios", descricao: "lista de advérbios com tradução e classificação por tipo", categoria: "Advérbios", tag: "Vocabulário" },
  { arquivo: "vocabulario-expressoes.html", titulo: "Vocabulário de Expressões", descricao: "expressões e estruturas frequentes com tradução, explicação e exemplos de uso", categoria: "Expressões", tag: "Vocabulário" },
  { arquivo: "sehr-viel.html", titulo: "Sehr × Viel", descricao: "diferença entre intensidade com sehr e quantidade ou frequência com viel", categoria: "Diferenças de uso", tag: "Vocabulário" },
  { arquivo: "waehrend-solange.html", titulo: "Während × Solange", descricao: "diferença entre simultaneidade com während e duração ou condição com solange", categoria: "Diferenças de uso", tag: "Gramática" },
  { arquivo: "uhr-stunde.html", titulo: "Uhr × Stunde", descricao: "diferença entre horário com Uhr e duração em horas com Stunde", categoria: "Diferenças de uso", tag: "Vocabulário" },
  { arquivo: "nach-zu-in.html", titulo: "Nach × Zu × In", descricao: "quando usar nach, zu e in para indicar destino em alemão", categoria: "Diferenças de uso", tag: "Gramática" },
  { arquivo: "vor-bevor.html", titulo: "Vor × Bevor", descricao: "diferença entre vor antes de substantivos e bevor antes de orações", categoria: "Diferenças de uso", tag: "Gramática" }
];
