const listaVerbos = [
    ["arbeiten", "trabalhar", "gearbeitet", "haben"],
    ["ankommen", "chegar", "angekommen", "sein"],
    ["anrufen", "ligar, telefonar", "angerufen", "haben"],
    ["anziehen", "vestir", "angezogen", "haben"],
    ["aufstehen", "levantar-se", "aufgestanden", "sein"],
    ["besuchen", "visitar", "besucht", "haben"],
    ["bleiben", "ficar", "geblieben", "sein"],
    ["denken", "pensar", "gedacht", "haben"],
    ["dürfen", "poder, ter permissão", "gedurft", "haben"],
    ["einkaufen", "fazer compras", "eingekauft", "haben"],
    ["essen", "comer", "gegessen", "haben"],
    ["fahren", "ir de veículo, dirigir", "gefahren", "sein / haben"],
    ["geben", "dar", "gegeben", "haben"],
    ["gehen", "ir", "gegangen", "sein"],
    ["haben", "ter", "gehabt", "haben"],
    ["helfen", "ajudar", "geholfen", "haben"],
    ["kaufen", "comprar", "gekauft", "haben"],
    ["kochen", "cozinhar", "gekocht", "haben"],
    ["können", "poder, conseguir", "gekonnt", "haben"],
    ["kommen", "vir", "gekommen", "sein"],
    ["lernen", "aprender, estudar", "gelernt", "haben"],
    ["lesen", "ler", "gelesen", "haben"],
    ["machen", "fazer", "gemacht", "haben"],
    ["mögen", "gostar", "gemocht", "haben"],
    ["müssen", "ter que, precisar", "gemusst", "haben"],
    ["nehmen", "pegar, tomar", "genommen", "haben"],
    ["regnen", "chover", "geregnet", "haben"],
    ["schwimmen", "nadar", "geschwommen", "sein / haben"],
    ["sehen", "ver", "gesehen", "haben"],
    ["sein", "ser, estar", "gewesen", "sein"],
    ["sollen", "dever", "gesollt", "haben"],
    ["sprechen", "falar", "gesprochen", "haben"],
    ["trinken", "beber", "getrunken", "haben"],
    ["warten", "esperar", "gewartet", "haben"],
    ["wissen", "saber", "gewusst", "haben"],
    ["wollen", "querer", "gewollt", "haben"],
    ["wohnen", "morar", "gewohnt", "haben"],
    ["werden", "tornar-se; virar", "geworden", "sein"],
    ["sich waschen", "lavar-se", "gewaschen", "haben"],
    ["sich anziehen", "vestir-se", "angezogen", "haben"],
    ["sich freuen", "alegrar-se / ficar feliz", "gefreut", "haben"],
    ["sich fühlen", "sentir-se", "gefühlt", "haben"],
    ["sich setzen", "sentar-se", "gesetzt", "haben"],
    ["sich beeilen", "apressar-se", "beeilt", "haben"],
    ["sich erinnern", "lembrar-se", "erinnert", "haben"],
    ["liegen", "estar deitado", "lag", "hat gelegen", "haben"],
    ["stehen", "estar em pé", "stand", "hat gestanden", "haben"],
    ["legen", "colocar deitado", "legte", "hat gelegt", "haben"],
    ["stellen", "colocar em pé", "stellte", "hat gestellt", "haben"],
    ["hängen", "pendurar / estar pendurado", "hing / hängte", "hat gehangen / hat gehängt", "haben"]
];
