const substantivos = [
    { substantivo: "Apfel", artigo: "der", plural: "die Äpfel", traducao: "Maçã", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Auto", artigo: "das", plural: "die Autos", traducao: "Carro", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Bahnhof", artigo: "der", plural: "die Bahnhöfe", traducao: "Estação", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Ball", artigo: "der", plural: "die Bälle", traducao: "Bola", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Berg", artigo: "der", plural: "die Berge", traducao: "Montanha", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Bier", artigo: "das", plural: "die Biere", traducao: "Cerveja", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Bild", artigo: "das", plural: "die Bilder", traducao: "Quadro / Imagem", generoOposto: "", pluralGeneroOposto: "", observacao: "Usada para imagens em geral, como fotos, ilustrações, gravuras etc." },
    { substantivo: "Blume", artigo: "die", plural: "die Blumen", traducao: "Flor", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Brot", artigo: "das", plural: "die Brote", traducao: "Pão", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Brücke", artigo: "die", plural: "die Brücken", traducao: "Ponte", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Bruder", artigo: "der", plural: "die Brüder", traducao: "Irmão", generoOposto: "die Schwester", pluralGeneroOposto: "die Schwestern", observacao: "" },
    { substantivo: "Buch", artigo: "das", plural: "die Bücher", traducao: "Livro", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Fahrrad", artigo: "das", plural: "die Fahrräder", traducao: "Bicicleta", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Farbe", artigo: "die", plural: "die Farben", traducao: "Cor", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Fenster", artigo: "das", plural: "die Fenster", traducao: "Janela", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Fleisch", artigo: "das", plural: "die Fleischsorten", traducao: "Carne", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Fluss", artigo: "der", plural: "die Flüsse", traducao: "Rio", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Freund", artigo: "der", plural: "die Freunde", traducao: "Amigo", generoOposto: "die Freundin", pluralGeneroOposto: "die Freundinnen", observacao: "" },
    { substantivo: "Garten", artigo: "der", plural: "die Gärten", traducao: "Jardim", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Gemälde", artigo: "das", plural: "die Gemälde", traducao: "Pintura / Quadro", generoOposto: "", pluralGeneroOposto: "", observacao: "Usada especificamente para uma pintura a óleo ou obra de arte em tela." },
    { substantivo: "Geschichte", artigo: "die", plural: "die Geschichten", traducao: "História / Conto", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Geschenk", artigo: "das", plural: "die Geschenke", traducao: "Presente", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Haus", artigo: "das", plural: "die Häuser", traducao: "Casa", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Himmel", artigo: "der", plural: "die Himmel", traducao: "Céu", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Hund", artigo: "der", plural: "die Hunde", traducao: "Cachorro", generoOposto: "die Hündin", pluralGeneroOposto: "die Hündinnen", observacao: "" },
    { substantivo: "Insel", artigo: "die", plural: "die Inseln", traducao: "Ilha", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Junge", artigo: "der", plural: "die Jungen", traducao: "Menino", generoOposto: "das Mädchen", pluralGeneroOposto: "die Mädchen", observacao: "" },
    { substantivo: "Kaffee", artigo: "der", plural: "die Kaffees", traducao: "Café", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Karte", artigo: "die", plural: "die Karten", traducao: "Mapa", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Käse", artigo: "der", plural: "die Käsesorten", traducao: "Queijo", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Kater", artigo: "der", plural: "die Kater", traducao: "Gato", generoOposto: "die Katze", pluralGeneroOposto: "die Katzen", observacao: "" },
    { substantivo: "Katze", artigo: "die", plural: "die Katzen", traducao: "Gato", generoOposto: "der Kater", pluralGeneroOposto: "die Kater", observacao: "" },
    { substantivo: "Kind", artigo: "das", plural: "die Kinder", traducao: "Criança", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Koffer", artigo: "der", plural: "die Koffer", traducao: "Mala", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Küche", artigo: "die", plural: "die Küchen", traducao: "Cozinha", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Kunde", artigo: "der", plural: "die Kunden", traducao: "Cliente", generoOposto: "die Kundin", pluralGeneroOposto: "die Kundinnen", observacao: "" },
    { substantivo: "Lehrer", artigo: "der", plural: "die Lehrer", traducao: "Professor", generoOposto: "die Lehrerin", pluralGeneroOposto: "die Lehrerinnen", observacao: "" },
    { substantivo: "Meer", artigo: "das", plural: "die Meere", traducao: "Mar", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Mutter", artigo: "die", plural: "die Mütter", traducao: "Mãe", generoOposto: "der Vater", pluralGeneroOposto: "die Väter", observacao: "" },
    { substantivo: "Nacht", artigo: "die", plural: "die Nächte", traducao: "Noite", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Nachbar", artigo: "der", plural: "die Nachbarn", traducao: "Vizinho", generoOposto: "die Nachbarin", pluralGeneroOposto: "die Nachbarinnen", observacao: "" },
    { substantivo: "Onkel", artigo: "der", plural: "die Onkel", traducao: "Tio", generoOposto: "die Tante", pluralGeneroOposto: "die Tanten", observacao: "" },
    { substantivo: "Park", artigo: "der", plural: "die Parks", traducao: "Parque", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Reise", artigo: "die", plural: "die Reisen", traducao: "Viagem", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Restaurant", artigo: "das", plural: "die Restaurants", traducao: "Restaurante", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Saft", artigo: "der", plural: "die Säfte", traducao: "Suco", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Schiff", artigo: "das", plural: "die Schiffe", traducao: "Navio / ou como termo geral para embarcações)", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Boot", artigo: "das", plural: "die Boote", traducao: "Barco", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Schule", artigo: "die", plural: "die Schulen", traducao: "Escola", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Schwester", artigo: "die", plural: "die Schwestern", traducao: "Irmã", generoOposto: "der Bruder", pluralGeneroOposto: "die Brüder", observacao: "" },
    { substantivo: "See", artigo: "der", plural: "die Seen", traducao: "Lago", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Stadt", artigo: "die", plural: "die Städte", traducao: "Cidade", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Stern", artigo: "der", plural: "die Sterne", traducao: "Estrela", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Student", artigo: "der", plural: "die Studenten", traducao: "Estudante", generoOposto: "die Studentin", pluralGeneroOposto: "die Studentinnen", observacao: "" },
    { substantivo: "Stuhl", artigo: "der", plural: "die Stühle", traducao: "Cadeira", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Suppe", artigo: "die", plural: "die Suppen", traducao: "Sopa", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Tante", artigo: "die", plural: "die Tanten", traducao: "Tia", generoOposto: "der Onkel", pluralGeneroOposto: "die Onkel", observacao: "" },
    { substantivo: "Tasche", artigo: "die", plural: "die Taschen", traducao: "Bolsa", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Tisch", artigo: "der", plural: "die Tische", traducao: "Mesa", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Tür", artigo: "die", plural: "die Türen", traducao: "Porta", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Uhr", artigo: "die", plural: "die Uhren", traducao: "Relógio", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Vogel", artigo: "der", plural: "die Vögel", traducao: "Pássaro", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Wahrheit", artigo: "die", plural: "die Wahrheiten", traducao: "Verdade", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Wald", artigo: "der", plural: "die Wälder", traducao: "Floresta", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Wasser", artigo: "das", plural: "die Wassersorten", traducao: "Água", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Wohnung", artigo: "die", plural: "die Wohnungen", traducao: "Apartamento", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Wolke", artigo: "die", plural: "die Wolken", traducao: "Núvem", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Zimmer", artigo: "das", plural: "die Zimmer", traducao: "Cômodo", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Tag", artigo: "der", plural: "die Tage", traducao: "Dia", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Woche", artigo: "die", plural: "die Wochen", traducao: "Semana", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Monat", artigo: "der", plural: "die Monate", traducao: "Mês", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Jahr", artigo: "das", plural: "die Jahre", traducao: "Ano", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Arzt", artigo: "der", plural: "die Ärzte", traducao: "Médico", generoOposto: "die Ärztin", pluralGeneroOposto: "die Ärztinnen", observacao: "" },
    { substantivo: "Arbeit", artigo: "die", plural: "die Arbeiten", traducao: "Trabalho", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Beruf", artigo: "der", plural: "die Berufe", traducao: "profissão", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Firma", artigo: "die", plural: "die Firmen", traducao: "Empresa", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Chef", artigo: "der", plural: "die Chefs", traducao: "Chefe", generoOposto: "die Chefin", pluralGeneroOposto: "die Chefinnen", observacao: "" },
    { substantivo: "Handy", artigo: "das", plural: "die Handys", traducao: "Celular", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Computer", artigo: "der", plural: "die Computer", traducao: "Computador", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Straße", artigo: "die", plural: "die Straßen", traducao: "Rua", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Weg", artigo: "der", plural: "die Wege", traducao: "Caminho", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Ecke", artigo: "die", plural: "die Ecken", traducao: "Esquina", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Laden", artigo: "der", plural: "die Läden", traducao: "Loja", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Geschäft", artigo: "das", plural: "die Geschäfte", traducao: "Negócio", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Kirche", artigo: "die", plural: "die Kirchen", traducao: "Igreja", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Krankenhaus", artigo: "das", plural: "die Krankenhäuser", traducao: "Hospital", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Apotheke", artigo: "die", plural: "die Apotheken", traducao: "Farmácia", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Flughafen", artigo: "der", plural: "die Flughäfen", traducao: "Aeroporto", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Zug", artigo: "der", plural: "die Züge", traducao: "Trem", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Flugzeug", artigo: "das", plural: "die Flugzeuge", traducao: "Avião", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Sonne", artigo: "die", plural: "die Sonnen", traducao: "Sol", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Mond", artigo: "der", plural: "die Monde", traducao: "Lua", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Schrank", artigo: "der", plural: "die Schränke", traducao: "Armário", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Bett", artigo: "das", plural: "die Betten", traducao: "Cama", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Sofa", artigo: "das", plural: "die Sofas", traducao: "Sofá", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Lampe", artigo: "die", plural: "die Lampen", traducao: "Lâmpada", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Spiegel", artigo: "der", plural: "die Spiegel", traducao: "Espelho", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Teppich", artigo: "der", plural: "die Teppiche", traducao: "Tapete", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Decke", artigo: "die", plural: "die Decken", traducao: "Cobertor/teto", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Boden", artigo: "der", plural: "die Böden", traducao: "Chão", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Wand", artigo: "die", plural: "die Wände", traducao: "Parede", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Treppe", artigo: "die", plural: "die Treppen", traducao: "Escada", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Kopf", artigo: "der", plural: "die Köpfe", traducao: "Cabeça", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Hand", artigo: "die", plural: "die Hände", traducao: "Mão", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Fuß", artigo: "der", plural: "die Füße", traducao: "Pé", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Auge", artigo: "das", plural: "die Augen", traducao: "Olho", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Ohr", artigo: "das", plural: "die Ohren", traducao: "Orelha", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Nase", artigo: "die", plural: "die Nasen", traducao: "Nariz", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Mund", artigo: "der", plural: "die Münder", traducao: "Boca", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Haar", artigo: "das", plural: "die Haare", traducao: "Cabelo", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Arm", artigo: "der", plural: "die Arme", traducao: "Braço", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Bein", artigo: "das", plural: "die Beine", traducao: "Perna", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Hemd", artigo: "das", plural: "die Hemden", traducao: "Camisa", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Hose", artigo: "die", plural: "die Hosen", traducao: "Calça", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Jacke", artigo: "die", plural: "die Jacken", traducao: "Jaqueta", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Schuh", artigo: "der", plural: "die Schuhe", traducao: "Sapato", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Mantel", artigo: "der", plural: "die Mäntel", traducao: "Casaco", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Rock", artigo: "der", plural: "die Röcke", traducao: "Saia", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Kleid", artigo: "das", plural: "die Kleider", traducao: "Vestido", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Mütze", artigo: "die", plural: "die Mützen", traducao: "Gorro/boné", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Socke", artigo: "die", plural: "die Socken", traducao: "Meia", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Gürtel", artigo: "der", plural: "die Gürtel", traducao: "Cinto", generoOposto: "", pluralGeneroOposto: "", observacao: "" },
    { substantivo: "Mann", artigo: "der", plural: "die Männer", traducao: "Homem", generoOposto: "die Frau", pluralGeneroOposto: "die Frauen", observacao: "" },
    { substantivo: "Frau", artigo: "die", plural: "die Frauen", traducao: "Mulher", generoOposto: "der Mann", pluralGeneroOposto: "die Männer", observacao: "" }
];