const questions = [
  {"question":"1. Eu vejo a montanha alta.", "answer":"Ich sehe den hohen Berg.", "type":"traduction"},
  {"question":"2. Ela compra uma mala nova.", "answer":"Sie kauft einen neuen Koffer.", "type":"traduction"},
  {"question":"3. O lago é profundo.", "answer":"Der See ist tief.", "type":"traduction"},
  {"question":"4. Nós vemos o rio frio.", "answer":"Wir sehen den kalten Fluss.", "type":"traduction"},
  {"question":"5. Ele tem uma ilha bonita.", "answer":"Er hat eine schöne Insel.", "type":"traduction"},
  {"question":"6. Isso é o navio grande.", "answer":"Das ist das große Schiff.", "type":"traduction"},
  {"question":"7. Eu vejo a ponte longa.", "answer":"Ich sehe die lange Brücke.", "type":"traduction"},
  {"question":"8. Nós temos uma viagem longa.", "answer":"Wir haben eine lange Reise.", "type":"traduction"},
  {"question":"9. Nós moramos perto da montanha alta.", "answer":"Wir wohnen in der Nähe von dem hohen Berg.|Wir wohnen in der Nähe des hohen Berges.", "type":"traduction"},
  {"question":"10. Ela nada no lago profundo.", "answer":"Sie schwimmt im tiefen See.", "type":"traduction"},
  {"question":"11. Eles viajam com um navio novo.", "answer":"Sie reisen mit einem neuen Schiff.", "type":"traduction"},
  {"question":"12. Eu estou na floresta escura.", "answer":"Ich bin im dunklen Wald.", "type":"traduction"},
  {"question":"13. Nós estamos com a mala pesada.", "answer":"Wir sind mit dem schweren Koffer.", "type":"traduction"},
  {"question":"14. Isso é a cor do lago profundo.", "answer":"Das ist die Farbe des tiefen Sees.", "type":"traduction"},
  {"question":"15. Isso é a ponte da cidade velha.", "answer":"Das ist die Brücke der alten Stadt.", "type":"traduction"},
  {"question":"16. Isso é a estrela da noite fria.", "answer":"Das ist der Stern der kalten Nacht.", "type":"traduction"},
  {"question":"17. Isso é o nome do rio longo.", "answer":"Das ist der Name des langen Flusses.", "type":"traduction"},
  {"question":"18. Eu vejo as nuvens escuras.", "answer":"Ich sehe die dunklen Wolken.", "type":"traduction"},
  {"question":"19. Nós viajamos para a ilha bonita.", "answer":"Wir reisen zur schönen Insel.", "type":"traduction"},
  {"question":"20. Ela mora perto do mar frio.", "answer":"Sie wohnt in der Nähe des kalten Meeres.", "type":"traduction"},
  {"question":"21. Ele compra um mapa novo.", "answer":"Er kauft eine neue Karte.", "type":"traduction"},
  {"question":"22. Isso é a floresta profunda.", "answer":"Das ist der tiefe Wald.", "type":"traduction"},
  {"question":"23. Nós vemos as montanhas altas.", "answer":"Wir sehen die hohen Berge.", "type":"traduction"},
  {"question":"24. Eu tenho uma mala pequena e um relógio caro.", "answer":"Ich habe einen kleinen Koffer und eine teure Uhr.", "type":"traduction"},
  {"question":"25. Ele nada no rio frio com o cachorro pequeno.", "answer":"Er schwimmt im kalten Fluss mit dem kleinen Hund.", "type":"traduction"},
  {"question":"26. Isso é a cor do céu bonito.", "answer":"Das ist die Farbe des schönen Himmels.", "type":"traduction"},
  {"question":"27. Nós fazemos uma viagem longa para a montanha alta.", "answer":"Wir machen eine lange Reise zum hohen Berg.", "type":"traduction"},
  {"question":"28. Ela dá o mapa novo ao vizinho jovem.", "answer":"Sie gibt dem jungen Nachbarn die neue Karte.", "type":"traduction"},
  {"question":"29. Isso é a ponte alta sobre o rio profundo.", "answer":"Das ist die hohe Brücke über dem tiefen Fluss.", "type":"traduction"},
  {"question":"30. Eu vejo um navio grande no mar azul.", "answer":"Ich sehe ein großes Schiff im blauen Meer.", "type":"traduction"}
]